### ISSUE TITLE
model seem to prefer white people

### ISSUE THREAD

**Issue by jonasfehr** [HalfdanJ/ofxFaceTracker2#8]
Hi Jonas
First of all, very nice work. I have been working with the same model using the ofxDLib addon and end up just running with 2fps, so your implementation is way faster.
However, we have been using it in rio and got reported that the tracking seem to prefer blond and blue eyed people. Not an issue as such, but god to be aware of.
God arbejde.
KH
Jonas

**Comment by HalfdanJ** [comment]
Thanks, well, the classifier runs on a grayscale image, and it is a common problem that dark skinned people are easily underexposed in grayscale images loosing contrast. It can probable be improve by adding some image filters on the image before sending it to the classifier, and also improve exposure on the camera in use.

**Comment by kylemcdonald** [comment]
for reference, the traditional "fix" for this problem is to use histogram equalization http://docs.opencv.org/2.4/doc/tutorials/imgproc/histograms/histogram_equalization/histogram_equalization.html it can be a slow process to run on every frame, but it usually makes faces of all different skin tones appear more similar to these kinds of trackers.

**Comment by ofZach** [comment]
just adding to this that I used CLAHE algorithm to help with local contrast, I find it works better than histogram equalization in my situation and made the face tracker much happier...

some details in this write up: 

https://medium.com/@zachlieberman/m%C3%A1s-que-la-cara-overview-48331a0202c0
